packages:
  - "packages/*"
  - "apps/*"
  - "internal/*"

catalog:
  typescript: 6.0.3
  "@types/node": ^25.6.0

onlyBuiltDependencies:
  - lefthook
  - esbuild

engineStrict: true

allowBuilds:
  esbuild: true
  lefthook: true
